### PR TITLE
Use unicode to draw borders

### PR DESCRIPTION
**Pull request by dveeden**
This uses unicode to draw the table borders

screenshot from 2015-06-07 23-52-13

### CODE REVIEW

**Comment by bazzilic** [comment]
What problem does this solve?

**Comment by dveeden** [comment]
The solid lines look better that the dashed lines.

This could be improved further by using different characters for the corners etc to get rid of the 'spikes' on the corners.

**Comment by bazzilic** [comment]
What I'm saying is that as this is supposed to run on multiple platforms, there might be numerous problems with console hosts that don't fully support unicode. That seriously outweighs the benefit of having a slightly better looking output.

**Comment by dveeden** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Pull request closed without merging**
