### PR TITLE
New version of the VATS algorithm (Largest Dependency Set First)

### PR DESCRIPTION
**Pull request by sensssz**
This pull request uses a new version of the VATS algorithm under version 5.7.

### CODE REVIEW

**Comment by grooverdan** [comment]
what is different about the new implementation?

**Comment by sensssz** [comment]
Hi, Daniel. In this new implementation we look at the sub-tree of each lock instead of just looking at the arrival time in the system. This gives us a more accurate yet efficient enough way of deciding which transaction to schedule first.

**Comment by sensssz** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by grooverdan** [comment]
@sensssz , great, keep up the good work! :+1:

**Pull request closed without merging**
