### PR TITLE
Bug #85819 Add AArch64 optimized crc32c implementation

### PR DESCRIPTION
**Pull request by guyuqi**
ARMv8 defines a set of optional CRC32/CRC32C instructions.
The CRC32 function for AArch64 that uses these instructions will optimize the performance rather than that uses table-based lookup.

I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

Bug #85819:  https://bugs.mysql.com/bug.php?id=85819

### CODE REVIEW

**Comment by akopytov** [comment]
A similar patch has been contributed in https://github.com/mysql/mysql-server/pull/31, but has never appeared in any released version.

**Comment by guyuqi** [comment]
I updated the crc32 optimization code. @akopytov 

ARMv8 defines PMULL crypto instruction. The new patch optimizes crc32c calculate with the PMULL instruction when available rather than original linear crc32 instructions.

The result of benchmark: 
Platform \ Case (millisecond)	| Software CRC	| AArch64 CRC Intrinsics	| AArch64 Crypto instruction
AMD seattle (Softiron)	        |1101.783	                |200.535	                        |114.509
Cavium ThunderX	                |1504.497	                |479.690	                        |286.274
Hisilicon Taishan( Huawei)	|1035.202	                |232.984	                        |115.580

It shows that the performance for CRC32 of innodb on AArch64 is better than linear crc32 instruction.

**Comment by guyuqi** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by houjibofa** [comment]
I test the patch in the Huawei Taishan 2208 board, but it compile failed. The error information is:

 error: #error You must enable AdvancedSIMD instructions to use arm_neon.h

the CPU information is

processor       : 63
BogoMIPS        : 100.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 2


Whether lacking some or not?

Thanks

**Comment by longlbj** [comment]
When running the mtr case: innodb.doublewrite, program terminated with signal SIGSEGV, Segmentation fault.
#1  0x00000000018d1f78 in my_write_core (sig=11) at ../mysys/stacktrace.c:249
#2  0x0000000000f43e14 in handle_fatal_signal (sig=11) at ../sql/signal_handler.cc:220
#3  <signal handler called>
#4  0x0000000000000000 in ?? ()
#5  0x0000000001a2e3d0 in page_zip_calc_checksum (data=0xffffb7f6b400, size=1024, algo=SRV_CHECKSUM_ALGORITHM_CRC32, use_legacy_big_endian=true) at ../storage/innobase/page/page0zip.cc:4957

**Pull request closed without merging**
