### PR TITLE
Adding fuzz directory and modifications to support it.

### PR DESCRIPTION
**Pull request by zjanati**
I am doing this pull request in behalf of @ChAlv (Christopher ALVES) , @catenacyber (Antoine PHILLIPE) , @Hitblow (Julien ZHAN) and me @zjanati (Zouhair JANATI IDRISSI). 
We worked on fuzzing mysql-server and reported the bugs that we found to oracle.
I recently sent to oracle the contributor agreement of all of us.

### CODE REVIEW

**Comment by zjanati** [comment]
Hi, I just sent to you an email with the Oracle Contribution Agreement with the address zouhair.janati.idrissi@gmail.com .

**Comment by catenacyber** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by ChAlv** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by zjanati** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

Le Mercredi, Mai 22, 2019 15:52 CEST, mysql-oca-bot <notifications@github.com> a écrit:
 
Hi, thank you for your contribution. Please confirm this code is submitted under the terms of the OCA (Oracle's Contribution Agreement) you have previously signed by cutting and pasting the following text as a comment:
"I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it."
Thanks

**Pull request closed without merging**
