### PR TITLE
make variables for slowlog dynamic on the special condition

### PR DESCRIPTION
**Pull request by dozhen0009**
For some special,we want to know all the request more detail,many like slowlog,rather than genlog,but some time It's difficult to reconnect all client

### CODE REVIEW

**Comment by wonderful1984** [comment]
That's exactly what I need

**Comment by dozhen0009** [comment]
My MySQL bug system user ***@***.***



https://github.com/mysql/mysql-server/pull/330





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mysql/mysql-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 晚上10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mysql/mysql-server] make variables for slowlog dynamic on the special condition (#330)





 
Hi, thank you for submitting this pull request. In order to consider your code we need you to sign the Oracle Contribution Agreement (OCA). Please review the details and follow the instructions at https://oca.opensource.oracle.com/
 Please make sure to include your MySQL bug system user (email) in the returned form.
 Thanks

**Comment by dozhen0009** [comment]
My MySQL bug system user ***@***.***



https://github.com/mysql/mysql-server/pull/330





发自我的iPhone


------------------ Original ------------------
From: mysql-oca-bot ***@***.***&gt;
Date: Wed,Mar 17,2021 10:52 PM
To: mysql/mysql-server ***@***.***&gt;
Cc: dozhen0009 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [mysql/mysql-server] make variables for slowlog dynamic on the special condition (#330)





 
Hi, thank you for submitting this pull request. In order to consider your code we need you to sign the Oracle Contribution Agreement (OCA). Please review the details and follow the instructions at https://oca.opensource.oracle.com/
 Please make sure to include your MySQL bug system user (email) in the returned form.
 Thanks

**Comment by dozhen0009** [comment]
> Hi, thank you for submitting this pull request. In order to consider your code we need you to sign the Oracle Contribution 
> Agreement (OCA). Please review the details and follow the instructions at https://oca.opensource.oracle.com/
> Please make sure to include your MySQL bug system user (email) in the returned form.
> Thanks
Hi, I have signed the OCA agreement and the bug system has also been updated. What's the next step?

**Comment by mysql-admin** [comment]
@dozhen0009 
Sorry for the delay in processing the OCA  - we are looking into it.
Once processed, you will be asked to confirm the contribution is under the OCA.

Thanks for contributing to MySQL
==Omer

**Comment by dozhen0009** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Pull request closed without merging**
