### PR TITLE
Merge pull request #1 from mysql/8.0

### PR DESCRIPTION
**Pull request by RahulSisondia**
8.0

### CODE REVIEW

**Comment by RahulSisondia** [comment]
Pull the latest changes

**Comment by boding1121** [comment]
- - 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by predators46** [comment]
sorry I wanted to ask if anyone made a patch mysql-8.0.2 on mysql-5.7

https://github.com/mysql/mysql-server/commit/a0f6a1453ec33c5c9dd5e6be24934c46f55805e3

**Comment by Anutrix** [comment]
Why is this open?

**Review by ihustle-hard — APPROVED** [review]
RahulSisondia:8.0

**Comment by RahulSisondia** [comment]
Closing this request

**Pull request closed without merging**
