### PR TITLE
mysql 8.0 audit plugin add examined_row_count/affected_row_count/return_row_count parameter

### PR DESCRIPTION
**Pull request by hongdongjian**
for mysql 8.0, audit plugin add examined_row_count/affected_row_count/return_row_count parameter

### CODE REVIEW

**Comment by hongdongjian** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by gkodinov** [comment]
Thank you for your attempt at contributing this enhancement. While it's a valid need, unfortunately this is not the way to implement it. Your change breaks ABI (application binary interface) around the audit plugin (as exemplified by the need to change the .pp file). Plus, it adds the new values for all audit plugins, regardless whether they need these or not.

I would suggest you consider turning the "push" model you have come up now into a "pull" model and extend e.g. https://dev.mysql.com/doc/dev/mysql-server/latest/structs__mysql__mysql__thd__attributes.html with the data you need.

**Comment by hongdongjian** [comment]
> Thank you for your attempt at contributing this enhancement. While it's a valid need, unfortunately this is not the way to implement it. Your change breaks ABI (application binary interface) around the audit plugin (as exemplified by the need to change the .pp file). Plus, it adds the new values for all audit plugins, regardless whether they need these or not.
> 
> I would suggest you consider turning the "push" model you have come up now into a "pull" model and extend e.g. https://dev.mysql.com/doc/dev/mysql-server/latest/structs__mysql__mysql__thd__attributes.html with the data you need.

Thank you for your reply and guidance. You are right. This is my new submission [https://github.com/mysql/mysql-server/pull/453]. Would you mind taking a look when you have time?

**Comment by hongdongjian** [comment]
> Thank you for your attempt at contributing this enhancement. While it's a valid need, unfortunately this is not the way to implement it. Your change breaks ABI (application binary interface) around the audit plugin (as exemplified by the need to change the .pp file). Plus, it adds the new values for all audit plugins, regardless whether they need these or not.
> 
> I would suggest you consider turning the "push" model you have come up now into a "pull" model and extend e.g. https://dev.mysql.com/doc/dev/mysql-server/latest/structs__mysql__mysql__thd__attributes.html with the data you need.

Hello, I would like to know if there is a similar way to obtain these variables from THD in version 5.7. This is regarding my previous submission [https://github.com/mysql/mysql-server/pull/450].

**Comment by gkodinov** [comment]
done. please try to stick to the same pull request if at all possible.

**Comment by gkodinov** [comment]
Sorry, but nothing like this in 5.7. 5.7 is to be going out of active development pretty soon. Let's focus on 8.0 :)

**Comment by hongdongjian** [comment]
> done. please try to stick to the same pull request if at all possible.

Thank you for your reply. I will take some time later to revise it.

**Comment by hongdongjian** [comment]
> Sorry, but nothing like this in 5.7. 5.7 is to be going out of active development pretty soon. Let's focus on 8.0 :)

understand

**Pull request closed without merging**
