### PR TITLE
Bug#78932: mysqldump --routines misquotes database names

### PR DESCRIPTION
**Pull request by FGasper**

### CODE REVIEW

**Comment by FGasper** [comment]
It would be great to get a backport of this to as many versions are supported … the breakage from this is pretty debilitating when you want a full backup of everything.

**Comment by FGasper** [comment]
I just sent in the OCA.

I didn’t see a place to indicate which issue I was submitting the form 
for, however..?

-FG

**Comment by mysql-admin** [comment]
Hi, 
Once we process the OCA and enter it into the system you will get another notice to confirm this contribution is under the OCA and then it will be associated with bug 78932

Thanks again for your contribution
==Omer

**Comment by FGasper** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

Sent from my android device.

-----Original Message-----

**Pull request closed without merging**
