### PR TITLE
Update sql_sort.h

### PR DESCRIPTION
**Pull request by zhoumengkang**
rowid sort  Place for NULL marker too

### CODE REVIEW

**Comment by zhoumengkang** [comment]
> Hi, thank you for submitting this pull request. In order to consider your code we need you to sign the Oracle Contribution Agreement (OCA). Please review the details and follow the instructions at http://www.oracle.com/technetwork/community/oca-486395.html
> Please make sure to include your MySQL bug system user (email) in the returned form.
> Thanks

I have registered an account （zhoumenkang@gmail.com）at bugs.mysql.com, and send the OCA email

**Comment by zhoumengkang** [comment]
> Hi, thank you for submitting this pull request. In order to consider your code we need you to sign the Oracle Contribution Agreement (OCA). Please review the details and follow the instructions at http://www.oracle.com/technetwork/community/oca-486395.html
> Please make sure to include your MySQL bug system user (email) in the returned form.
> Thanks

I wonder why no one's pull request was merged? you know, that's very inspiring.

**Comment by zhoumengkang** [comment]
@mysql-oca-bot Is something wrong? Why is there no further reply to my pull request? Looking forward to your reply.

**Comment by mysql-admin** [comment]
@zhoumengkang : Hi Checking why there is a delay in processing
Sorry for the delay
==Omer

**Comment by zhoumengkang** [comment]
@mysql-admin it doesn't matter

**Comment by mysql-admin** [comment]
@zhoumengkang : I'm sorry but we didn't get an OCA from you and sending you an email to zhoumenkang@gmail.com - bounced.  
Please resend me the OCA to omer.barnir@oracle.com 

Thanks
==Omer

**Comment by zhoumengkang** [comment]
@mysql-admin I am very sorry that there is a letter missing from the email address I wrote in the previous content. my account is zhoumengkang@gmail.com , I have sent you a new email

**Comment by zhoumengkang** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Pull request closed without merging**
