### PR TITLE
Few improvements related to CPU cache line size and padding

### PR DESCRIPTION
**Pull request by akopytov**
Bug #79636: CACHE_LINE_SIZE should be 128 on AArch64
Bug #79637: Hard-coded cache line size
Bug #79638: Reconcile CACHE_LINE_SIZE with CPU_LEVEL1_DCACHE_LINESIZE
Bug #79652: Suspicious padding in srv_conc_t
- changed CPU_LEVEL1_DCACHE_LINESIZE to default to 128 bytes on POWER
  and AArch64 architectures in cases when no value could be detected
  by CMake using getconf
- changed pfs_global.h to assume CPU_LEVEL1_DCACHE_LINESIZE is always
  defined (and throw a compile-time error if it's not)
- changed CACHE_LINE_SIZE definition in ut0counter.h to be an alias of
  CPU_LEVEL1_DCACHE_LINESIZE
- changed a number of hard-coded 64-byte cache line size values in the
  InnoDB code
- fixed insufficient padding for srv_conc members in srv0conc.cc

### CODE REVIEW

**Comment by akopytov** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by grooverdan** [comment]
thanks @akopytov

**Comment by akopytov** [comment]
I made a minor change to the patch fixing the compilation error on systems where `getconf LEVEL1_DCACHE_LINESIZE` returns 0. Therefore re-submitting the PR.

**Comment by grooverdan** [comment]
in storage/perfschema/pfs_global.h is there a reason PFS_ALIGNEMENT wasn't defined to CPU_LEVEL1_DCACHE_LINESIZE?

**Comment by akopytov** [comment]
No reason, just an oversight. I'll fix.

**Comment by akopytov** [comment]
Submitted https://github.com/mysql/mysql-server/pull/66. Thanks.

**Pull request closed without merging**
