### PR TITLE
Fix scramble algorithm docs

### PR DESCRIPTION
**Pull request by kelunik**
Also fixes two typos in error messages.

### CODE REVIEW

**Comment by kelunik** [comment]
@mysql-oca-bot I sent a mail, but haven't received a response. I can't fill the form, because there are obligatory fields I can't provide a value for.

**Comment by mysql-admin** [comment]
@kelunik, 
Sorry to hear you had an issue with the OCA form
Please email me directly with the details (omer.barnir@oracle.com)

Thanks
==Omer
P.S Reopening the PR to allow more time for this to be resolved

**Comment by kelunik** [comment]
@mysql-admin Thanks! I just sent the mail.

**Comment by kelunik** [comment]
@mysql-admin Please re-open, as the OCA is finally done and approved now.

**Comment by mysql-admin** [comment]
Sorry this dropped off the radar - reopening
==Omer

**Comment by kelunik** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Pull request closed without merging**
