### PR TITLE
Update SQL modes in the comments in statements_event.h

### PR DESCRIPTION
**Pull request by dongwook-chan**
Existing comments int statements_event.h provides outdated values for sql mode system variables.
This PR updates the values and adds new variables to prevent confusion.

### CODE REVIEW

**Comment by dongwook-chan** [comment]
I've reviewed and signed OCA.

**Comment by dongwook-chan** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by baiwfg2** [comment]
@dongwook-chan Hi, have you tracked whether your patch is merged or not ? I don't see it in 8.0.  When does community merge this kind of external PR ?

**Comment by dongwook-chan** [comment]
@baiwfg2 
https://bugs.mysql.com/bug.php?id=105144
You can see the status of the patch on the link above.
It's in 'verified' status ever since I reported this patch...
Replication module seems quite unpopular and the patch only fixed comment so...
I also reported a few bug fixes on replication protocol, but got no response so far...;
https://bugs.mysql.com/bug.php?id=105297
https://bugs.mysql.com/bug.php?id=105300

**Comment by baiwfg2** [comment]
Sigh ..

**Pull request closed without merging**
