### PR TITLE
Report timing with more precision

### PR DESCRIPTION
**Pull request by dveeden**
```
mysql> select sleep(0.123);
+--------------+
| sleep(0.123) |
+--------------+
|            0 |
+--------------+
1 row in set (0.123 sec)
```

### CODE REVIEW

**Comment by dveeden** [comment]
The other option is to change the return type of start_timer from ulong to double.

**Comment by dveeden** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by grooverdan** [comment]
since the client is linked to ../libmysql/libmysqlclient.a which contains mysys, using my_timer_init/my_timer_milliseconds/my_timer_microseconds/ my_timer_nanoseconds from mysys/my_rdtsc.c might be the neatest cross platform solution.

**Comment by dveeden** [comment]
@grooverdan I agree. Closing this PR in favour of #113

**Pull request closed without merging**
