### PR TITLE
Fix the spelling of preceding, specified, received and additionally

### PR DESCRIPTION
**Pull request by ottok**
I am tired of fixing the same bugs in different downstream packages I work with, so I decided to push my fixes directly to the source at Oracle MySQL. This simple spelling fix is my first in a series of multiple fixes.

I hereby grant Oracle full rights regarding this contribution. Please accept my fix!

### CODE REVIEW

**Comment by morgo** [comment]
Hi Otto, thank you for the contribution!

We are not currently accepting pull requests from GitHub.  May I suggest filing a bug report on bugs.mysql.com?  

(I would also be happy to do so on your behalf.)

**Comment by ottok** [comment]
Ok, thanks. I filed the pull request now at http://bugs.mysql.com/bug.php?id=75084

**Comment by morgo** [comment]
Thank you Otto!  I will close this pull request for now.

**Comment by ottok** [comment]
For the record: fixed in commit https://github.com/mysql/mysql-server/commit/60aeb14d778f78cdf696d4af5cfe6dd5a7dc57be

**Pull request closed without merging**
